Added main and options menues
RylaD303/BayGanyo pull request #14
Opened 2023-05-01 15:26 UTC by ViktorKapra

2023-05-01 19:41 UTC, RylaD303 requested changes
Everything seems alrighty, just do 3 small things, please:
 1. Remove the PlayerBullet changes. A bullet should not be extending a hitbox. A bullet is an entity by it's own. It should contatin a hitbox, but is not a hitbox.
 2. Please move the menu script in the script directories (options_menu.gd, Menu.gd).
 3. Preferably use pascal case for naming classes. Should be "OptionsMenu.gd". And use Snake case for scenes.

2023-05-01 19:41 UTC, RylaD303 commented on src/objects/mainMenu/Menu.gd
> +
Add class_name, please.

2023-05-01 19:41 UTC, RylaD303 commented on src/objects/mainMenu/options_menu.gd
> +
Same here, add a class_name.

2023-05-01 21:16 UTC, ViktorKapra commented
Тhe issues have been noted and fixed. Thanks for the feedback

2023-05-02 12:35 UTC, RylaD303 approved these changes
Well done!

2023-05-02 12:35 UTC, merged